"""Grants the Databricks App's service principal the Unity Catalog permissions it needs
to access structured data (the tables underlying Genie).

Background: when structured_agent on the Serving Endpoint side calls Genie, it fails
with `PERMISSION_DENIED: ... No access to 'adventureworks_dataagent.sales.customer' ...`
(full details in docs/DEVELOPMENT_JOURNAL.md case 11 and
docs/VERIFICATION_2026-07-27.md Step 7e). This happens because the service principal
Databricks Apps auto-generates on deploy hasn't been granted access to the underlying
tables — the App has its own service principal
(`client.apps.get(app_name).service_principal_client_id`), and when Genie actually
executes the SQL it generated, it runs under the caller's permissions; if the caller
lacks SELECT/USE CATALOG/USE SCHEMA, Genie rejects the query.

**Which tables/functions to grant is imported directly from `ops/structured/setup_genie.py`'s
`GENIE_TABLES`/`REQUIRED_FUNCTIONS` — this file does not maintain a second copy of that
list.** One script owns "which tables are attached to the Genie Space", the other owns
"who gets granted access to query those tables"; keeping two separately-maintained lists
makes it easy to update one and forget the other (e.g. `setup_genie.py` adds a new table
but this script isn't updated to GRANT it — that fails in production with a permission
error that isn't obvious from reading the code). As it stands now, changing
`GENIE_TABLES` in `setup_genie.py` automatically flows through to this script — no
manual sync needed.

**Grants are per-table SELECT (not schema-level), per-function EXECUTE (not
schema-level)** — more precise than an earlier version of this script (which did a
blanket `GRANT SELECT ON SCHEMA sales`), granting access only to the tables/functions
Genie actually needs, so a schema-level grant can't accidentally expose tables that
aren't listed in `GENIE_TABLES`. `USE CATALOG`/`USE SCHEMA` are still granted at the
schema level, since they're just prerequisites for the access path (they don't expose
any data themselves, just "this catalog/schema is visible" — no need to make those
per-table either).

This script only grants; it doesn't revoke or re-grant to other identities — if it turns
out these grants still aren't sufficient (e.g. the identity actually in effect isn't the
App's service principal but the Serving Endpoint's own runtime identity, which currently
has no official API to look up), that needs separate investigation and is out of scope
for this script.

Usage: python -m ops.grant_app_permissions
"""

from __future__ import annotations

from src.config import settings
from src.db_client import get_workspace_client
from ops.sql_utils import run_statement
from ops.structured.setup_genie import GENIE_TABLES, REQUIRED_FUNCTIONS


def _grant_statements(principal: str) -> list[str]:
    statements = [f"GRANT USE CATALOG ON CATALOG {settings.uc_catalog} TO `{principal}`"]

    # Tables in GENIE_TABLES belong to different schemas (currently sales/person); grant
    # USE SCHEMA once per distinct schema actually used, and SELECT per table.
    schemas = sorted({table.split(".", 1)[0] for table in GENIE_TABLES})
    for schema in schemas:
        statements.append(
            f"GRANT USE SCHEMA ON SCHEMA {settings.uc_catalog}.{schema} TO `{principal}`"
        )
    for table in GENIE_TABLES:
        statements.append(
            f"GRANT SELECT ON TABLE {settings.uc_catalog}.{table} TO `{principal}`"
        )

    # SQL generated by Genie calls the business-rule functions, which needs EXECUTE (not
    # SELECT), granted per function.
    statements.append(
        f"GRANT USE SCHEMA ON SCHEMA {settings.uc_catalog}.{settings.uc_function_schema} TO `{principal}`"
    )
    for fn in REQUIRED_FUNCTIONS:
        statements.append(
            f"GRANT EXECUTE ON FUNCTION {settings.uc_catalog}.{settings.uc_function_schema}.{fn} TO `{principal}`"
        )

    return statements


def main() -> None:
    settings.require("sql_warehouse_id", "databricks_app_name", "uc_catalog")
    client = get_workspace_client()

    app = client.apps.get(settings.databricks_app_name)
    principal = app.service_principal_client_id
    if not principal:
        raise RuntimeError(
            f"No service_principal_client_id found for app {settings.databricks_app_name}. "
            "Confirm the App has already been successfully created (its service principal "
            "is only generated after the first deployment completes)."
        )
    print(f"App service principal: {app.service_principal_name} ({principal})")
    print(f"This run grants access to {len(GENIE_TABLES)} tables + {len(REQUIRED_FUNCTIONS)} functions "
          f"(sourced from GENIE_TABLES/REQUIRED_FUNCTIONS in ops/structured/setup_genie.py)\n")

    for stmt in _grant_statements(principal):
        run_statement(client, stmt)
        print(f"Executed: {stmt}")

    print("\nGrants complete.")


if __name__ == "__main__":
    main()
